# Generated by Django 4.2.6 on 2023-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('Gmail', models.CharField(max_length=50, verbose_name='Gmail')),
                ('Contrasena', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('nombreAlumno', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
            ],
        ),
    ]
